version: '2.1'
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_BASEPATH}/transmission:/config
      - ${BASEPATH}/Download:/downloads
      - ${BASEPATH}/Download/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_BASEPATH}/sonarr:/config
      - ${BASEPATH}/Series:/tv
      - ${BASEPATH}/Download:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_BASEPATH}/radarr:/config
      - ${BASEPATH}/Films:/movies
      - ${BASEPATH}/Download:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_BASEPATH}/bazarr:/config
      - ${BASEPATH}/Films:/movies
      - ${BASEPATH}/Series:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:nightly
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_BASEPATH}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_BASEPATH}/readarr:/config
      - ${BASEPATH}/Fichiers/Manga:/manga
      - ${BASEPATH}/Fichiers/Comics:/comics
      - ${BASEPATH}/Fichiers/Books:/books
      - ${BASEPATH}/Download:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ${CONFIG_BASEPATH}/nginx:/etc/nginx/conf.d
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
      - VERSION=docker
    volumes:
      - ${CONFIG_BASEPATH}/plex:/config
      - ${BASEPATH}/Series:/tv
      - ${BASEPATH}/Films:/movies
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    ports:
      - 8191:8191
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_BASEPATH}/bazarr:/config
      - ${BASEPATH}/Films:/movies #optional
      - ${BASEPATH}/Series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    environment:
      - PUID=1026
      - GUID=100
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_BASEPATH}/kavita:/config
      - ${BASEPATH}/Fichiers/Manga:/manga
      - ${BASEPATH}/Fichiers/Comics:/comics
      - ${BASEPATH}/Fichiers/Books:/books
    ports:
      - 8383:5000
    restart: unless-stopped
